In [1]:
import numpy as np

 # Creating numpy arrays
 
 ## from python lists
 *************************************

In [2]:
arr=np.array([1,4,2,5,3 ]) 

In [3]:
arr

array([1, 4, 2, 5, 3])

In [4]:
np.array([3,14,8.9,5.3])

array([ 3. , 14. ,  8.9,  5.3])

In [5]:
np.array([3,14,89,53],dtype='float32')

array([ 3., 14., 89., 53.], dtype=float32)

## From Scratch

In [6]:
np.zeros((10,3),dtype='float32')

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]], dtype=float32)

In [7]:
np.ones((4,10),dtype=int)

array([[1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1, 1, 1, 1, 1, 1]])

In [8]:
np.ones((4,10,3),dtype=int)

array([[[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1],
        [1, 1, 1]]])

 Available data type in Numpy
 -------------------------
 ************************

In [9]:
#Create a 3x5 arrray filled with 3
np.full((3,5),3)

array([[3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3]])

In [10]:
# creat an array filled with a linear sequence
#Start at 0 ,ending at20,stepping2
np.arange(0,20,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
#create a 3x3 array of uniformly distributed
#random values between zero and one
np.random.random((3,3))

array([[0.52543191, 0.05890042, 0.22541861],
       [0.36330095, 0.71791819, 0.45796737],
       [0.08768404, 0.73623252, 0.13009691]])

In [13]:
#create a 3x3 array of normally distributed random values
#with mean 0 and standerd deviation 1
np.random.normal(0,1,(3,3))

array([[-0.65931857, -0.36459967, -1.36335318],
       [ 0.38328288, -0.22449969, -0.76165817],
       [ 1.95630267,  0.12863651, -0.15205307]])

In [14]:
#create a 3x3 array of random integers in the interval [0,0
np.random.randint(0,10,(3,3))

array([[5, 1, 9],
       [5, 8, 0],
       [8, 2, 0]])

In [15]:
#create a 5x5 identity matrix
np.eye(5,5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [16]:
#Create an uninitialized array of three integers
#The values will be whatever happens already exist at that memory location
np.empty((3,3))

array([[0.65931857, 0.36459967, 1.36335318],
       [0.38328288, 0.22449969, 0.76165817],
       [1.95630267, 0.12863651, 0.15205307]])

## Numpy Array Attributes
***************************************

In [17]:
x=np.zeros((3,4,5),dtype=int)
x

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]])

In [18]:
print('x ndim', x.ndim)
print('x shape',x.shape)
print('x size',x.size)
print('x dtype', x.dtype)

x ndim 3
x shape (3, 4, 5)
x size 60
x dtype int32


Array indexing
------------
******************************

In [19]:
x1=np.array([1,9,6,3,2,5,8,7,4,1,4,5,6,9])
x1

array([1, 9, 6, 3, 2, 5, 8, 7, 4, 1, 4, 5, 6, 9])

In [20]:
x1[-1]


9

In [21]:
x1[5]

5

In [22]:
x2=np.array([[6,3,1,1],[9,8,7,4],[7,0,2,3]])
x2

array([[6, 3, 1, 1],
       [9, 8, 7, 4],
       [7, 0, 2, 3]])

In [23]:
x2[0,1]

3

In [24]:
x2[2,0]

7

In [25]:
x2[1,0]

9

Array Sclicing: Accesing Subarrays
------------------

one-dimensional subarrays
************************************************

In [26]:
x=np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [27]:
x[1:5]

array([1, 2, 3, 4])

In [28]:
x[4:8]

array([4, 5, 6, 7])

In [29]:
x[:3]

array([0, 1, 2])

In [30]:
x1=np.random.randint(1,600,10)
x1

array([294, 595, 551,  52, 592, 175, 281, 298,  37,  80])

In [31]:
x1[:6]

array([294, 595, 551,  52, 592, 175])

In [32]:
x1[1::2]

array([595,  52, 175, 298,  80])

In [33]:
x1[::-2]

array([ 80, 298, 175,  52, 595])

 Multidimensional Subarrays
 ------------------

In [34]:
x=np.array([[1,2,3,8],[2,5,8,7],[2,4,6,9]])
x

array([[1, 2, 3, 8],
       [2, 5, 8, 7],
       [2, 4, 6, 9]])

In [35]:
x[0:2,2:4]

array([[3, 8],
       [8, 7]])

Accessing array rows and columns
----------------------
*********************************

In [36]:
print(x[:,0])#FIRST COLOUMN OF X

[1 2 2]


In [37]:
print(x[0,:])#FIRST ROW OF X

[1 2 3 8]


In [38]:
print([x[0]])#EQUIVALENT OF X[0,:]

[array([1, 2, 3, 8])]


Creating copies of arrays
---------------------
**********************************

In [39]:
x=np.array([[1,2,3,8],[2,5,8,7],[2,4,6,9]])
x

array([[1, 2, 3, 8],
       [2, 5, 8, 7],
       [2, 4, 6, 9]])

In [46]:
xsub=x[:2,:2].copy()
xsub

array([[5, 2],
       [2, 5]])

In [47]:
xsub[0,0]=5
xsub

array([[5, 2],
       [2, 5]])

In [48]:
x # HERE WE CHANGE THE VALUE IT WAS 1 NOW IT'S =5

array([[5, 2, 3, 8],
       [2, 5, 8, 7],
       [2, 4, 6, 9]])

Reshaping of Arrays
--------------------------
*************************************

In [49]:
grid =np.arange(1,11)
grid

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [52]:
grid =grid.reshape((2,5))
grid

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [53]:
grid=np.arange(1,11).reshape((2,5)) #alternative way
grid

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [55]:
grid=np.arange(0,12).reshape((6,2))
grid

array([[ 0,  1],
       [ 2,  3],
       [ 4,  5],
       [ 6,  7],
       [ 8,  9],
       [10, 11]])

In [56]:
x=np.array([1,2,3])
#ROW VECTOR VIA RESHAPE
x.reshape((1,3))

array([[1, 2, 3]])

In [57]:
 x.reshape((1,3)).shape

(1, 3)

In [58]:
#ROW VECTOR VIA RESHAPE (ALTERNATIVE WAY)
#ANOTHER WAY LIKE RESHAPE
x[np.newaxis,:]

array([[1, 2, 3]])

In [59]:
# COUMN VECTOR VIA NEWAXIS
x[:,np.newaxis].shape

(3, 1)

In [60]:
grid.reshape((2,3,2))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

In [61]:
grid.reshape((2,3,-1))

array([[[ 0,  1],
        [ 2,  3],
        [ 4,  5]],

       [[ 6,  7],
        [ 8,  9],
        [10, 11]]])

# Array Concatenation
***************************************
[1  2  3]

[3  2  1]

[1  2  3  3  2  1]

In [62]:
x=np.array([1,2,3])
y=np.array([3,2,1])
np.concatenate([x,y])

array([1, 2, 3, 3, 2, 1])

In [63]:
z=[2,4,8]
np.concatenate((x,y,z))

array([1, 2, 3, 3, 2, 1, 2, 4, 8])

In [64]:
#FOR 2D ARRAY
x=np.full((2,3),1)
y=np.full((2,3),9)
print(x)
print('----------------')
print(y)


[[1 1 1]
 [1 1 1]]
----------------
[[9 9 9]
 [9 9 9]]


In [71]:
np.concatenate((x,y),axis=0)

array([[1, 1, 1],
       [1, 1, 1],
       [9, 9, 9],
       [9, 9, 9]])

In [70]:
np.concatenate((x,y),axis=0).shape

(4, 3)

In [69]:
#CONCATENATE ALONG THE SECOND AXIS (ZERO-INDEX)
np.concatenate([x,y],axis=1)

array([[1, 1, 1, 9, 9, 9],
       [1, 1, 1, 9, 9, 9]])

Spilting of Arrays
-------------------------
******************************
x=[1,2,3,4,5,6,7,8]


[1,2,3]  [4,5]  [6,7,8]
*****************************************

In [91]:
x=[1,2,3,4,5,6,7,8]
x1,x2,x3,x4=np.split(x,[3,5,7])# N spilt points lead to N +1 subarrays
print(x1,x2,x3,x4)

[1 2 3] [4 5] [6 7] [8]
